/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.Editors;

import java.awt.Point;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author edison
 */
public class AuditoryEditor extends javax.swing.JFrame {

    /**
     * Creates new form AuditoryEditor
     */
        private Connection cn;
    private PreparedStatement ps;
    private Statement st;
    private ResultSet rs;
    private int itemID;
    private File f;
    private byte[] imageChosedToByteArray;
    private JFileChooser chooser = new JFileChooser();
    public AuditoryEditor() {
        
    }
    public AuditoryEditor(int id){
        initComponents();
        setSize(400, 223);
        setResizable(false);
        itemID = id;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            String getData = "Select * from cvarst.AuditoryTest where id = '"+itemID+"'";
            rs = st.executeQuery(getData);
            while(rs.next()){
            
                
                 
                 String name = rs.getString("AudioName");
                 String path = rs.getString("AudioPath");
//                   Image img = icon.getImage();
//                    BufferedImage bi = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
//                    Graphics g = bi.createGraphics();
//                   g.drawImage(img, 0, 0, questionImage.getWidth(), questionImage.getHeight(), null);
//                    ImageIcon result = new ImageIcon(bi);
                    
                   audioNameField.setText(name);
                   audioPathField.setText(path);
            }
        }
        
        catch(Exception e){
            
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        audioPathField = new javax.swing.JTextField();
        audioNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        attachFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Editors/modify_title.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 100, 33);

        jLabel3.setBackground(java.awt.Color.darkGray);
        jLabel3.setOpaque(true);
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 60);
        getContentPane().add(audioPathField);
        audioPathField.setBounds(110, 120, 220, 28);
        getContentPane().add(audioNameField);
        audioNameField.setBounds(110, 80, 270, 28);

        jLabel1.setText("Path");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 130, 51, 18);

        jLabel2.setText("Audio Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 100, 18);

        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(modifyButton);
        modifyButton.setBounds(10, 180, 130, 28);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(250, 180, 142, 28);

        attachFileButton.setText("+");
        attachFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attachFileButton);
        attachFileButton.setBounds(340, 120, 43, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed

        String path = audioPathField.getText().toString();
        try{

            ps = cn.prepareStatement("");
            st = cn.createStatement();

            try {
                ps = cn.prepareStatement("update cvarst.AuditoryTest SET AudioName = ?, AudioPath = ? where id = ?");
                ps.setString(1, audioNameField.getText().toString());
                ps.setString(2, path);
                ps.setInt(3, itemID);
                ps.executeUpdate();
                cn.close();
                ps.close();
                JOptionPane.showMessageDialog(null, "Modified de item Successfully");
 

            } catch (Exception ex) {
                Logger.getLogger(ColorBlindEditor.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.dispose();

        }
        catch(Exception e){

            e.printStackTrace();
        }

    }//GEN-LAST:event_modifyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void attachFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachFileButtonActionPerformed
        // TODO add your handling code here:

        chooser.showOpenDialog(null);
        chooser.setDialogTitle("Open Image File");
        f =  chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        audioPathField.setText(filename);

    }//GEN-LAST:event_attachFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditoryEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditoryEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditoryEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditoryEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuditoryEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachFileButton;
    private javax.swing.JTextField audioNameField;
    private javax.swing.JTextField audioPathField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton modifyButton;
    // End of variables declaration//GEN-END:variables
}
