/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.Pickers;

import java.awt.Image;
import java.awt.Point;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import project.RegistrationForm;

/**
 *
 * @author edison
 */
public class ColorBlindPicker extends javax.swing.JFrame {

    /**
     * Creates new form ColorBlindPicker
     */
    private File f;
    private byte[] imageChosedToByteArray;
    private JFileChooser chooser = new JFileChooser();
    public ColorBlindPicker() {
        initComponents();
        setResizable(false);
        setSize(457, 468);
//        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        attachedFileField = new javax.swing.JTextField();
        attachFileButton = new javax.swing.JButton();
        answerField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        questionImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pickers/title_add.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 40, 33);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(30, 420, 92, 28);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(270, 420, 142, 28);

        attachedFileField.setEnabled(false);
        getContentPane().add(attachedFileField);
        attachedFileField.setBounds(90, 320, 270, 28);

        attachFileButton.setText("+");
        attachFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attachFileButton);
        attachFileButton.setBounds(370, 320, 43, 28);
        getContentPane().add(answerField);
        answerField.setBounds(90, 360, 270, 28);

        jLabel1.setText("Photo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 330, 51, 18);

        jLabel2.setText("Answer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 370, 57, 18);

        jLabel3.setBackground(java.awt.Color.darkGray);
        jLabel3.setOpaque(true);
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 457, 60);

        questionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Pickers/NoImageIcon.png"))); // NOI18N
        getContentPane().add(questionImage);
        questionImage.setBounds(100, 90, 260, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
        
    }//GEN-LAST:event_jLabel3MouseDragged

    private void attachFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachFileButtonActionPerformed
        // TODO add your handling code here:
        
        chooser.showOpenDialog(null);
        chooser.setDialogTitle("Open Image File");
        f =  chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        attachedFileField.setText(filename);
        
        ImageIcon image = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(questionImage.getWidth(), questionImage.getHeight(), Image.SCALE_REPLICATE));
        questionImage.setIcon(image);
        try{
            File imageFile = new File(filename);
            FileInputStream fis = new FileInputStream(imageFile);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);
            }
            imageChosedToByteArray = bos.toByteArray();
            
            
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_attachFileButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        Connection cn;
        PreparedStatement ps;
        Statement st;
        String answer = answerField.getText().toString();
       try{
       Class.forName("com.mysql.jdbc.Driver");
       cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
       ps = cn.prepareStatement("");
       st = cn.createStatement(); 
       
               try {
     
           String getCount = "select id from cvarst.ColorblindTest";
           int count = 0;
            ResultSet resultSet = st.executeQuery(getCount);
            while(resultSet.next()){
                count = resultSet.getInt("id");
            }
            
            ps = cn.prepareStatement("insert into cvarst.ColorblindTest (id, Picture, Answer) values"
                    + "(?, ?, ?)");
            
            ps.setInt(1, count + 1);
            ps.setObject(2, imageChosedToByteArray);
            ps.setString(3, answer);
            ps.executeUpdate();
            cn.close();
            ps.close();
            JOptionPane.showMessageDialog(null, "Added de item Successfully");
            
        } catch (SQLException ex) {
            Logger.getLogger(ColorBlindPicker.class.getName()).log(Level.SEVERE, null, ex);
        }

            this.dispose();
            
           
            
            
        }
        catch(Exception e){
        
                e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorBlindPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorBlindPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorBlindPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorBlindPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorBlindPicker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField answerField;
    private javax.swing.JButton attachFileButton;
    private javax.swing.JTextField attachedFileField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel questionImage;
    // End of variables declaration//GEN-END:variables
}
