/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

import net.proteanit.sql.DbUtils;

/**
 *
 * @author edison
 */
public class ClearanceForm extends javax.swing.JFrame {

    /**
     * Creates new form ClearanceForm
     */
     private JFileChooser chooser = new JFileChooser();
     private File f;
    private Connection cn;
    private PreparedStatement ps;
    private Statement st;
    private ResultSet rs;
    public ClearanceForm() {
        initComponents();
        setSize(1209, 738);
        setResizable(false);
//        formTitle.setHorizontalAlignment(SwingConstants.CENTER);
        Dimension size = fromDate.getCalendarPreferredSize();
        size.width += 90;
        size.height += 60;
        fromDate.setCalendarPreferredSize(size);
        toDate.setCalendarPreferredSize(size);
        detailsPane.setVisible(false);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        fromDate.setDateFormat(dateFormat);
        toDate.setDateFormat(dateFormat);
         String getData = "Select id,photo, firstname, middlename, lastname, result, code, date_registered from cvarst.registration";
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            rs = st.executeQuery(getData);
            clearanceTable.setModel(DbUtils.resultSetToTableModel(rs));
            clearanceTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            
            

        }
           catch(Exception e){
           e.printStackTrace();}
         
         
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsPane = new javax.swing.JInternalFrame();
        photoDetail = new javax.swing.JLabel();
        nameDetail = new javax.swing.JLabel();
        genderDetail = new javax.swing.JLabel();
        ageDetail = new javax.swing.JLabel();
        addressDetail = new javax.swing.JLabel();
        heightDetail = new javax.swing.JLabel();
        weightDetail = new javax.swing.JLabel();
        bloodDetail = new javax.swing.JLabel();
        resCodeDetail = new javax.swing.JLabel();
        vehicleUsedDetail = new javax.swing.JLabel();
        licenseNumberDetail = new javax.swing.JLabel();
        dateRegisteredDetail = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        detailsPhoto = new javax.swing.JLabel();
        detailsName = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        middleName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clearanceTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fromDate = new datechooser.beans.DateChooserCombo();
        toDate = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setUndecorated(true);
        getContentPane().setLayout(null);

        detailsPane.setBackground(java.awt.Color.white);
        detailsPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailsPane.setVisible(true);
        detailsPane.getContentPane().setLayout(null);

        photoDetail.setBackground(java.awt.Color.gray);
        photoDetail.setOpaque(true);
        detailsPane.getContentPane().add(photoDetail);
        photoDetail.setBounds(10, 20, 130, 110);

        nameDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        nameDetail.setText("Justin Edison B. Escabart");
        detailsPane.getContentPane().add(nameDetail);
        nameDetail.setBounds(150, 20, 230, 30);

        genderDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        genderDetail.setText("Male");
        detailsPane.getContentPane().add(genderDetail);
        genderDetail.setBounds(150, 50, 230, 30);

        ageDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        ageDetail.setText("34 years old");
        detailsPane.getContentPane().add(ageDetail);
        ageDetail.setBounds(150, 80, 230, 30);

        addressDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        addressDetail.setText("Address: Navotas City");
        detailsPane.getContentPane().add(addressDetail);
        addressDetail.setBounds(10, 150, 350, 30);

        heightDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        heightDetail.setText("Height: 142 cm");
        detailsPane.getContentPane().add(heightDetail);
        heightDetail.setBounds(10, 180, 370, 30);

        weightDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        weightDetail.setText("Weight: 321 lbs");
        detailsPane.getContentPane().add(weightDetail);
        weightDetail.setBounds(10, 210, 360, 30);

        bloodDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        bloodDetail.setText("Blood Type: O");
        detailsPane.getContentPane().add(bloodDetail);
        bloodDetail.setBounds(10, 240, 360, 30);

        resCodeDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        resCodeDetail.setText("Res Code: 3");
        detailsPane.getContentPane().add(resCodeDetail);
        resCodeDetail.setBounds(10, 270, 360, 30);

        vehicleUsedDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        vehicleUsedDetail.setText("Vehicle Used: Toyota Vios");
        detailsPane.getContentPane().add(vehicleUsedDetail);
        vehicleUsedDetail.setBounds(10, 300, 370, 30);

        licenseNumberDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        licenseNumberDetail.setText("License Number: JED3023");
        detailsPane.getContentPane().add(licenseNumberDetail);
        licenseNumberDetail.setBounds(10, 330, 370, 30);

        dateRegisteredDetail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        dateRegisteredDetail.setText("Date Registered: 2019-3-7");
        detailsPane.getContentPane().add(dateRegisteredDetail);
        dateRegisteredDetail.setBounds(10, 360, 370, 30);

        jButton6.setText("Dismiss");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        detailsPane.getContentPane().add(jButton6);
        jButton6.setBounds(273, 450, 110, 28);

        jSeparator2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        detailsPane.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 140, 360, 40);

        getContentPane().add(detailsPane);
        detailsPane.setBounds(390, 140, 400, 520);

        jLabel3.setBackground(new java.awt.Color(210, 21, 21));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1160, 0, 50, 20);

        jLabel1.setBackground(new java.awt.Color(26, 26, 26));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 20);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        detailsPhoto.setBackground(java.awt.Color.lightGray);
        detailsPhoto.setOpaque(true);
        jPanel4.add(detailsPhoto);
        detailsPhoto.setBounds(14, 14, 132, 114);

        detailsName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailsName.setText("No Details");
        jPanel4.add(detailsName);
        detailsName.setBounds(2, 134, 156, 18);

        jButton5.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        jButton5.setText("More Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(14, 158, 132, 28);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(1040, 110, 160, 200);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("Search by Names");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.gray);
        jLabel8.setText("First Name");

        firstName.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.gray);
        jLabel9.setText("Middle Name");

        middleName.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.gray);
        jLabel10.setText("Last Name");

        lastName.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(middleName, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(firstName)
                            .addComponent(lastName))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 110, 560, 200);

        jPanel5.setBackground(new java.awt.Color(23, 23, 23));

        formTitle.setBackground(new java.awt.Color(23, 23, 23));
        formTitle.setFont(new java.awt.Font("Sawasdee", 0, 48)); // NOI18N
        formTitle.setForeground(java.awt.Color.white);
        formTitle.setText("Clearances");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 20, 1210, 80);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        clearanceTable.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        clearanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "asasa", "saas", "For VErification", "no"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Picture", "Name", "Code", "Result"
            }
        ));
        clearanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearanceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clearanceTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1190, 360);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 320, 1190, 360);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N

        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("Search by Date");

        fromDate.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(85, 85, 85),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(85, 85, 85),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(85, 85, 85),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(85, 85, 85),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    try {
        fromDate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2018, 8, 17),
            new java.util.GregorianCalendar(2018, 8, 17))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    fromDate.setFieldFont(new java.awt.Font("Trebuchet MS", java.awt.Font.PLAIN, 16));
    fromDate.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            fromDateOnSelectionChange(evt);
        }
    });

    toDate.setFieldFont(new java.awt.Font("Umpush", java.awt.Font.PLAIN, 16));
    toDate.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            toDateOnSelectionChange(evt);
        }
    });

    jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
    jLabel6.setForeground(java.awt.Color.gray);
    jLabel6.setText("From");

    jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
    jLabel7.setForeground(java.awt.Color.gray);
    jLabel7.setText("To");

    jButton4.setText("🔍");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addContainerGap(313, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(22, 22, 22))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jButton4)
            .addContainerGap())
    );

    getContentPane().add(jPanel3);
    jPanel3.setBounds(590, 110, 430, 200);

    jButton1.setText("🔄");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton1);
    jButton1.setBounds(1050, 690, 70, 28);

    jButton2.setText("❌");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton2);
    jButton2.setBounds(1130, 690, 70, 28);

    jButton7.setText("Complete Status");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton7);
    jButton7.setBounds(890, 690, 150, 28);

    jButton3.setText("Print Clearance");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton3);
    jButton3.setBounds(720, 690, 160, 28);

    background.setBackground(java.awt.Color.white);
    background.setOpaque(true);
    getContentPane().add(background);
    background.setBounds(0, 20, 1210, 720);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:

        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(HomeForm.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        update_Table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomeForm hF = new HomeForm();
        hF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
      private void update_Table(){
           PreparedStatement prepared = null;
        Connection conn;
        
    try{

        
       
    String sql = "Select id, photo, firstname, middlename, lastname, result, code, date_registered from cvarst.registration";
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
    prepared = conn.prepareStatement(sql);
    rs = prepared.executeQuery();
    clearanceTable.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    
    }
    finally{
    try{
    
    rs.close();
    prepared.close();
    
    }
    catch (Exception e){}
    }
    
    
    try{prepared.close();}
    catch(Exception e){}
    }
          private JDialog showMessage(String s, String title, String type){
    
            JOptionPane jop = new JOptionPane(s, (type.equals("S")) ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE);
            JDialog dialog = jop.createDialog(title);
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            return dialog;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel)clearanceTable.getModel();         // Specify target table//

       
            
         chooser.showOpenDialog(null);
        chooser.setDialogTitle("Save File");
        f =  chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
//        attachedFileField.setText(filename);
            
            String file_name = filename;
            
            
            
            Document document = new Document();
            try {
                PdfWriter.getInstance(document, new FileOutputStream(file_name));
                document.open();
                Paragraph header = new Paragraph("                                 "
                        + "                       LTO Clearance Summary Report");
                document.add(header);
                try {
                    ps = cn.prepareStatement("SELECT Doctor, Clinic_Name from cvarst.RegisteredDoctors WHERE id = ?");
                    ps.setInt(1, User.getUserID());
                    ps.executeQuery();
                    ResultSet rs = ps.executeQuery();
                    while(rs.next())
                    {
                        Paragraph doc = new Paragraph("\n\nDoctor:\t                 "+rs.getString("Doctor")+ "                                                "
                                + "              \t\t\tDate Proceed: "+ fromDate.getText());
                        document.add(doc);
                        Paragraph clinic = new Paragraph("\nClinic:\t                   "+rs.getString("Clinic_Name"));
                        document.add(clinic);
                        Paragraph dateFrom = new Paragraph("\nDate From:\t           "+fromDate.getText());
                        document.add(dateFrom);
                        Paragraph dateTo = new Paragraph("\nDate To :\t              "+toDate.getText());
                        document.add(dateTo);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ClearanceForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                Paragraph spacing = new Paragraph("\n\n");
                document.add(spacing);
                PdfPTable table = new PdfPTable(8);
                table.setWidthPercentage(100);
                PdfPCell cell = new PdfPCell(new Phrase("Exam ID"));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase("Exam Date"));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase("Name"));
                table.addCell(cell);

                cell = new PdfPCell(new Phrase("Color Blind"));
                table.addCell(cell);

                cell = new PdfPCell(new Phrase("Vision"));
                table.addCell(cell);

                cell = new PdfPCell(new Phrase("Auditory"));
                table.addCell(cell);

                cell = new PdfPCell(new Phrase("Status"));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase("Remarks"));
                table.addCell(cell);
                try {
//                    String qry = "SELECT * from cvarst.registration WHERE date_registered between '"+fromDate.getText()+
//                            "' AND '"+ toDate.getText()+"'";
                    
//                                        String qry = "SELECT * from cvarst.registration WHERE date_registered between '"+fromDate.getText()+
//                            "' AND '"+ toDate.getText()+"'";
                  String getData = "Select id, photo, firstname, middlename, lastname, result, code, ColorblindScore, AuditoryScore, date_registered from cvarst.registration where date_registered between '"+ fromDate.getText() +"' AND '"+ toDate.getText() +"'";
                    ResultSet rs = st.executeQuery(getData);
                    int count = 0;
                    while(rs.next()){
                        count++;
                        cell = new PdfPCell(new Phrase(rs.getString("id")));
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase(rs.getString("date_registered"))); //declaration ng data type is int
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase(rs.getString("firstname")+rs.getString("middlename")+rs.getString("lastname")));
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase(rs.getString("ColorblindScore") == null  ? "No Data" : rs.getString("ColorblindScore").toString())); 
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase("Left/Right"));
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase(rs.getString("AuditoryScore") == null  ? "No data" : rs.getString("AuditoryScore").toString())); 
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase(rs.getString("result")));
                        table.addCell(cell);
                        cell = new PdfPCell(new Phrase("Remarks"));
                        table.addCell(cell);
                    }
                        cell = new PdfPCell(new Phrase("Total clearances:              "+ count));
                        cell.setColspan(8);
                        table.addCell(cell);
                        showMessage("Report Summary Saved", "Success", "S");
                } catch (SQLException ex) {
                    Logger.getLogger(ClearanceForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                document.add(table);

                document.close();
                
                
            } catch (DocumentException ex) {
                Logger.getLogger(ClearanceForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    

        }
        catch(FileNotFoundException ex) {
            Logger.getLogger(ClearanceForm.class.getName()).log(Level.SEVERE,null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    public void searchedResult() throws ParseException{
    
     String from = fromDate.getText(), to = toDate.getText() ;
//              SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
//              Date date = new Date();
//              String dateFrom = dateFormat.format(from);
//              String dateTo = dateFormat.format(to);
              
              
    Date now = new Date();

    //SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
   
//    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//    Date newDate = fromDate.getSelectedDate();
//System.out.println(dateFormat.format(newDate));



    //String date = format.format(fromDate.getText());
    //Date myDate = new Date(date);
    //java.sql.Date sqlDate = new java.sql.Date(myDate.getTime());

     
//      String getData = "Select photo, firstname, middlename, lastname, result, code, date_registered from cvarst.registration where date_registered = '"+ dateFormat.format(newDate) +"'";
    

    String getData = "Select id, photo, firstname, middlename, lastname, result, code, date_registered from cvarst.registration "
            + "where firstname LIKE '" + firstName.getText() + "%' "
            + "AND middlename LIKE '" + middleName.getText() + "%' "
            + "AND lastname LIKE '" + lastName.getText() + "%'"
            + " AND date_registered between '"+ fromDate.getText() +"' AND '"+ toDate.getText() +"'";

         try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            rs = st.executeQuery(getData);
            clearanceTable.setModel(DbUtils.resultSetToTableModel(rs));
            clearanceTable.getColumnModel().getColumn(0).setPreferredWidth(0);

        }
           catch(Exception e){
           JOptionPane.showMessageDialog(null, e);}
    }
    private void fromDateOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_fromDateOnSelectionChange
     
            // TODO add your handling code here:
            
      
        
        
        
    }//GEN-LAST:event_fromDateOnSelectionChange

    private void toDateOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_toDateOnSelectionChange
        
            // TODO add your handling code here:
           
        
    }//GEN-LAST:event_toDateOnSelectionChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            searchedResult();
        } catch (ParseException ex) {
            Logger.getLogger(ClearanceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clearanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearanceTableMouseClicked
        // TODO add your handling code here:
        
        if(clearanceTable.getSelectedRow() != 0){
        
            String name = clearanceTable.getValueAt(clearanceTable.getSelectedRow(), 3).toString();
            ImageIcon icon = new ImageIcon((byte[]) clearanceTable.getValueAt(clearanceTable.getSelectedRow(), 1));
            detailsName.setText(name);
            detailsPhoto.setIcon(icon);
        }
     
    }//GEN-LAST:event_clearanceTableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(clearanceTable.getSelectedRowCount() != 0){
            
            
            int id = Integer.valueOf(clearanceTable.getValueAt(clearanceTable.getSelectedRow(), 0).toString());
           String query = "Select * from cvarst.registration where id = '"+ id +"'";
           try{
               ResultSet rs = st.executeQuery(query);
               while(rs.next()){     
               ImageIcon icon = new ImageIcon((byte[]) clearanceTable.getValueAt(clearanceTable.getSelectedRow(), 1));
               photoDetail.setIcon(icon);
                 
               nameDetail.setText(rs.getString("firstname") + " " + rs.getString("middlename") + " " + rs.getString("lastname"));
               genderDetail.setText(rs.getString("gender"));
               ageDetail.setText(String.valueOf(rs.getInt("Age")) + " years old");
               //
               addressDetail.setText("Address: " + rs.getString("address"));
               heightDetail.setText("Height: " + String.valueOf(rs.getString("height")) + " cm");
               weightDetail.setText("Weight: " + String.valueOf(rs.getString("weight")) + " lbs");
               bloodDetail.setText("Blood Type: " + rs.getString("blood_type"));
               resCodeDetail.setText("Res Code: " + String.valueOf(rs.getString("res_code")));
               vehicleUsedDetail.setText("Vehicle Used: " + rs.getString("vehicle_used"));
               licenseNumberDetail.setText("License Number " + rs.getString("license_number"));
               dateRegisteredDetail.setText("Date Registered: " + rs.getString("date_registered"));
               }
           
           }
           catch(Exception e){
               e.printStackTrace();
           }
            
            detailsPane.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        detailsPane.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
  
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel)clearanceTable.getModel();         // Specify target table//

            
            if(clearanceTable.getSelectedRowCount()!= 0){
                int selectedRowIndex = clearanceTable.getSelectedRow();
                 int id = Integer.valueOf((model.getValueAt(selectedRowIndex, 0).toString()));
              try {

                ps = cn.prepareStatement("UPDATE cvarst.registration SET code = ?, result = ?, uploaded = ? Where id = ?");
                ps.setString(1, "Verified");
                ps.setString(2, "Complete");
                ps.setString(3, "Yes");
                ps.setInt(4, id);
                ps.executeUpdate();
                update_Table();
            }
            catch(Exception e) {
                 
            }}
            else{
            
               showMessage("No row selected", "Notice", "E");
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClearanceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressDetail;
    private javax.swing.JLabel ageDetail;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bloodDetail;
    private javax.swing.JTable clearanceTable;
    private javax.swing.JLabel dateRegisteredDetail;
    private javax.swing.JLabel detailsName;
    private javax.swing.JInternalFrame detailsPane;
    private javax.swing.JLabel detailsPhoto;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel formTitle;
    private datechooser.beans.DateChooserCombo fromDate;
    private javax.swing.JLabel genderDetail;
    private javax.swing.JLabel heightDetail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel licenseNumberDetail;
    private javax.swing.JTextField middleName;
    private javax.swing.JLabel nameDetail;
    private javax.swing.JLabel photoDetail;
    private javax.swing.JLabel resCodeDetail;
    private datechooser.beans.DateChooserCombo toDate;
    private javax.swing.JLabel vehicleUsedDetail;
    private javax.swing.JLabel weightDetail;
    // End of variables declaration//GEN-END:variables
}
