/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import project.Tests.ColorBlindTestForm;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;




/**
 *
 * @author edison
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
 
    private Connection cn;
    private PreparedStatement ps;
    private Statement st;
    BufferedImage bi;
    String nFile;
  
         
    public RegistrationForm() {
       
        initComponents();
        setSize(875, 551);
        setResizable(false);
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setForeground(Color.LIGHT_GRAY);
        rightBiometricHighlighted.setVisible(false);
        leftBiometricHighlighted.setVisible(false);
        cameraButtonHighlighed.setVisible(false);
        proceedButtonHighlighted.setVisible(false);
        cancelButtonHighlighted.setVisible(false);
        jPanel1.setVisible(false);
        selectButtonHighlighted.setVisible(false);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            
            JOptionPane.showMessageDialog(null, "connected.");
            
           
            
            
        }
        catch(Exception e){
        
                e.printStackTrace();
        }
 
        genderCB.setOpaque(false);
     
    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cameraFeed = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        selectButtonHighlighted = new javax.swing.JLabel();
        selectButton = new javax.swing.JLabel();
        dateChooserBirthdate = new cambodia.raven.DateChooser();
        weightLabel1 = new javax.swing.JLabel();
        heightLabel1 = new javax.swing.JLabel();
        heightText = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        vehicleUsedText = new javax.swing.JTextField();
        weightText1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        licenseNoText = new javax.swing.JTextField();
        licenceNumberLabel = new javax.swing.JLabel();
        vehicleUsedLabel = new javax.swing.JLabel();
        resCodeLabel = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        resCodeCB = new javax.swing.JComboBox<>();
        bloodTypeCB = new javax.swing.JComboBox<>();
        genderCB = new javax.swing.JComboBox<>();
        ageLabel = new javax.swing.JLabel();
        birthdateLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        ageText = new javax.swing.JTextField();
        birthdateText = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        addressLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        addressText = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        middlenameLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lastnameText = new javax.swing.JTextField();
        middlenameText = new javax.swing.JTextField();
        firstnameText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JLabel();
        cancelButtonHighlighted = new javax.swing.JLabel();
        proceedButtonHighlighted = new javax.swing.JLabel();
        proceedButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cameraButtonHighlighed = new javax.swing.JLabel();
        rightBiometricHighlighted = new javax.swing.JLabel();
        leftBiometricHighlighted = new javax.swing.JLabel();
        rightBiometric = new javax.swing.JLabel();
        leftBiometric = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cameraButton = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        heightLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        cameraFeed.setLayout(null);
        getContentPane().add(cameraFeed);
        cameraFeed.setBounds(30, 80, 190, 160);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });
        jPanel1.setLayout(null);

        selectButtonHighlighted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/selectButton.png"))); // NOI18N
        selectButtonHighlighted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectButtonHighlightedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectButtonHighlightedMouseExited(evt);
            }
        });
        jPanel1.add(selectButtonHighlighted);
        selectButtonHighlighted.setBounds(1, 230, 260, 29);

        selectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selectButton.png"))); // NOI18N
        selectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectButtonMouseEntered(evt);
            }
        });
        jPanel1.add(selectButton);
        selectButton.setBounds(1, 230, 260, 29);
        jPanel1.add(dateChooserBirthdate);
        dateChooserBirthdate.setBounds(0, 0, 260, 225);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 240, 260, 260);

        weightLabel1.setForeground(java.awt.Color.lightGray);
        weightLabel1.setText("lbs");
        getContentPane().add(weightLabel1);
        weightLabel1.setBounds(500, 268, 30, 30);

        heightLabel1.setForeground(java.awt.Color.lightGray);
        heightLabel1.setText("cm");
        getContentPane().add(heightLabel1);
        heightLabel1.setBounds(370, 270, 30, 30);

        heightText.setBackground(new java.awt.Color(14, 122, 138));
        heightText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        heightText.setForeground(new java.awt.Color(255, 255, 255));
        heightText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        heightText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                heightTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                heightTextFocusLost(evt);
            }
        });
        heightText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heightTextMouseClicked(evt);
            }
        });
        getContentPane().add(heightText);
        heightText.setBounds(290, 270, 80, 28);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(580, 360, 260, 10);

        vehicleUsedText.setBackground(new java.awt.Color(14, 122, 138));
        vehicleUsedText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        vehicleUsedText.setForeground(new java.awt.Color(255, 255, 255));
        vehicleUsedText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vehicleUsedText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vehicleUsedTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vehicleUsedTextFocusLost(evt);
            }
        });
        vehicleUsedText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleUsedTextMouseClicked(evt);
            }
        });
        getContentPane().add(vehicleUsedText);
        vehicleUsedText.setBounds(290, 330, 280, 28);

        weightText1.setBackground(new java.awt.Color(14, 122, 138));
        weightText1.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        weightText1.setForeground(new java.awt.Color(255, 255, 255));
        weightText1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        weightText1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weightText1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                weightText1FocusLost(evt);
            }
        });
        weightText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weightText1MouseClicked(evt);
            }
        });
        getContentPane().add(weightText1);
        weightText1.setBounds(420, 270, 80, 28);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(290, 300, 110, 6);

        licenseNoText.setBackground(new java.awt.Color(14, 122, 138));
        licenseNoText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        licenseNoText.setForeground(new java.awt.Color(255, 255, 255));
        licenseNoText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        licenseNoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                licenseNoTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                licenseNoTextFocusLost(evt);
            }
        });
        licenseNoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                licenseNoTextMouseClicked(evt);
            }
        });
        getContentPane().add(licenseNoText);
        licenseNoText.setBounds(580, 330, 260, 28);

        licenceNumberLabel.setForeground(java.awt.Color.lightGray);
        licenceNumberLabel.setText("License Number");
        getContentPane().add(licenceNumberLabel);
        licenceNumberLabel.setBounds(580, 310, 110, 18);

        vehicleUsedLabel.setForeground(java.awt.Color.lightGray);
        vehicleUsedLabel.setText("Vehicle Used");
        getContentPane().add(vehicleUsedLabel);
        vehicleUsedLabel.setBounds(290, 310, 110, 18);

        resCodeLabel.setForeground(java.awt.Color.lightGray);
        resCodeLabel.setText("Res. code");
        getContentPane().add(resCodeLabel);
        resCodeLabel.setBounds(670, 250, 90, 18);

        bloodTypeLabel.setForeground(java.awt.Color.lightGray);
        bloodTypeLabel.setText("Blood Type");
        getContentPane().add(bloodTypeLabel);
        bloodTypeLabel.setBounds(560, 250, 90, 18);

        weightLabel.setForeground(java.awt.Color.lightGray);
        weightLabel.setText("Weight");
        getContentPane().add(weightLabel);
        weightLabel.setBounds(420, 250, 70, 18);

        genderLabel.setForeground(java.awt.Color.lightGray);
        genderLabel.setText("Gender");
        getContentPane().add(genderLabel);
        genderLabel.setBounds(170, 140, 80, 18);

        resCodeCB.setBackground(new java.awt.Color(14, 122, 138));
        resCodeCB.setMaximumRowCount(5);
        resCodeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        resCodeCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 122, 138)));
        resCodeCB.setOpaque(false);
        resCodeCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resCodeCBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                resCodeCBFocusLost(evt);
            }
        });
        getContentPane().add(resCodeCB);
        resCodeCB.setBounds(670, 270, 170, 35);

        bloodTypeCB.setBackground(new java.awt.Color(14, 122, 138));
        bloodTypeCB.setMaximumRowCount(5);
        bloodTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "O", "AB" }));
        bloodTypeCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 122, 138)));
        bloodTypeCB.setOpaque(false);
        bloodTypeCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bloodTypeCBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bloodTypeCBFocusLost(evt);
            }
        });
        getContentPane().add(bloodTypeCB);
        bloodTypeCB.setBounds(560, 270, 100, 35);

        genderCB.setBackground(new java.awt.Color(14, 122, 138));
        genderCB.setMaximumRowCount(2);
        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 122, 138)));
        genderCB.setOpaque(false);
        genderCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                genderCBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                genderCBFocusLost(evt);
            }
        });
        getContentPane().add(genderCB);
        genderCB.setBounds(558, 210, 100, 35);

        ageLabel.setForeground(java.awt.Color.lightGray);
        ageLabel.setText("Age");
        getContentPane().add(ageLabel);
        ageLabel.setBounds(670, 190, 80, 18);

        birthdateLabel.setForeground(java.awt.Color.lightGray);
        birthdateLabel.setText("Birthdate");
        getContentPane().add(birthdateLabel);
        birthdateLabel.setBounds(290, 190, 80, 18);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(670, 240, 170, 10);

        ageText.setBackground(new java.awt.Color(14, 122, 138));
        ageText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        ageText.setForeground(new java.awt.Color(255, 255, 255));
        ageText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ageText.setFocusable(false);
        getContentPane().add(ageText);
        ageText.setBounds(670, 210, 170, 28);

        birthdateText.setBackground(new java.awt.Color(14, 122, 138));
        birthdateText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        birthdateText.setForeground(new java.awt.Color(255, 255, 255));
        birthdateText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        birthdateText.setFocusable(false);
        birthdateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthdateTextMouseClicked(evt);
            }
        });
        getContentPane().add(birthdateText);
        birthdateText.setBounds(290, 210, 260, 28);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(290, 240, 260, 10);

        addressLabel.setForeground(java.awt.Color.lightGray);
        addressLabel.setText("Address");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(290, 130, 80, 18);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(290, 180, 550, 10);

        addressText.setBackground(new java.awt.Color(14, 122, 138));
        addressText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        addressText.setForeground(new java.awt.Color(255, 255, 255));
        addressText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addressText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTextFocusLost(evt);
            }
        });
        getContentPane().add(addressText);
        addressText.setBounds(290, 150, 550, 28);

        lastnameLabel.setForeground(java.awt.Color.lightGray);
        lastnameLabel.setText("Last name");
        getContentPane().add(lastnameLabel);
        lastnameLabel.setBounds(650, 80, 120, 18);

        middlenameLabel.setForeground(java.awt.Color.lightGray);
        middlenameLabel.setText("Middle name");
        getContentPane().add(middlenameLabel);
        middlenameLabel.setBounds(470, 80, 120, 18);

        firstnameLabel.setForeground(java.awt.Color.lightGray);
        firstnameLabel.setText("First name");
        getContentPane().add(firstnameLabel);
        firstnameLabel.setBounds(290, 80, 80, 18);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(290, 120, 170, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(650, 120, 190, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(470, 120, 170, 10);

        lastnameText.setBackground(new java.awt.Color(14, 122, 138));
        lastnameText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        lastnameText.setForeground(new java.awt.Color(255, 255, 255));
        lastnameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lastnameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameTextFocusLost(evt);
            }
        });
        getContentPane().add(lastnameText);
        lastnameText.setBounds(650, 95, 190, 28);

        middlenameText.setBackground(new java.awt.Color(14, 122, 138));
        middlenameText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        middlenameText.setForeground(new java.awt.Color(255, 255, 255));
        middlenameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        middlenameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middlenameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middlenameTextFocusLost(evt);
            }
        });
        getContentPane().add(middlenameText);
        middlenameText.setBounds(470, 95, 170, 28);

        firstnameText.setBackground(new java.awt.Color(14, 122, 138));
        firstnameText.setFont(new java.awt.Font("URW Gothic L", 0, 17)); // NOI18N
        firstnameText.setForeground(new java.awt.Color(255, 255, 255));
        firstnameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        firstnameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameTextFocusLost(evt);
            }
        });
        getContentPane().add(firstnameText);
        firstnameText.setBounds(290, 95, 170, 28);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelButton.png"))); // NOI18N
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(650, 480, 190, 29);

        cancelButtonHighlighted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/cancelButton.png"))); // NOI18N
        cancelButtonHighlighted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonHighlightedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonHighlightedMouseExited(evt);
            }
        });
        getContentPane().add(cancelButtonHighlighted);
        cancelButtonHighlighted.setBounds(650, 480, 190, 29);

        proceedButtonHighlighted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/proceedButton.png"))); // NOI18N
        proceedButtonHighlighted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedButtonHighlightedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedButtonHighlightedMouseExited(evt);
            }
        });
        getContentPane().add(proceedButtonHighlighted);
        proceedButtonHighlighted.setBounds(40, 480, 190, 29);

        proceedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proceedButton.png"))); // NOI18N
        proceedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedButtonMouseEntered(evt);
            }
        });
        getContentPane().add(proceedButton);
        proceedButton.setBounds(40, 480, 190, 29);

        jLabel4.setFont(new java.awt.Font("Ubuntu Condensed", 0, 9)); // NOI18N
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel4.setText("Fingerprint");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 285, 170, 10);

        cameraButtonHighlighed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/cameraButton.png"))); // NOI18N
        cameraButtonHighlighed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cameraButtonHighlighedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cameraButtonHighlighedMouseExited(evt);
            }
        });
        getContentPane().add(cameraButtonHighlighed);
        cameraButtonHighlighed.setBounds(30, 250, 190, 29);

        rightBiometricHighlighted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/rightBiometricsButton.png"))); // NOI18N
        rightBiometricHighlighted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightBiometricHighlightedMouseExited(evt);
            }
        });
        getContentPane().add(rightBiometricHighlighted);
        rightBiometricHighlighted.setBounds(124, 297, 94, 29);

        leftBiometricHighlighted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/leftBiometricsButton.png"))); // NOI18N
        leftBiometricHighlighted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftBiometricHighlightedMouseExited(evt);
            }
        });
        getContentPane().add(leftBiometricHighlighted);
        leftBiometricHighlighted.setBounds(30, 297, 94, 29);

        rightBiometric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rightBiometricsButton.png"))); // NOI18N
        rightBiometric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightBiometricMouseEntered(evt);
            }
        });
        getContentPane().add(rightBiometric);
        rightBiometric.setBounds(124, 297, 94, 29);

        leftBiometric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leftBiometricsButton.png"))); // NOI18N
        leftBiometric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftBiometricMouseEntered(evt);
            }
        });
        getContentPane().add(leftBiometric);
        leftBiometric.setBounds(30, 297, 94, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundBiometrics.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 280, 190, 50);

        cameraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cameraButton.png"))); // NOI18N
        cameraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cameraButtonMouseEntered(evt);
            }
        });
        getContentPane().add(cameraButton);
        cameraButton.setBounds(30, 250, 190, 29);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(420, 300, 110, 10);
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(290, 360, 280, 10);

        heightLabel.setForeground(java.awt.Color.lightGray);
        heightLabel.setText("Height");
        getContentPane().add(heightLabel);
        heightLabel.setBounds(290, 250, 70, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MinimizeButton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(831, 0, 50, 20);

        jLabel1.setBackground(new java.awt.Color(3, 72, 83));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registrationBackground.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 880, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:

        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(HomeForm.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void leftBiometricMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftBiometricMouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(Color.WHITE);
        leftBiometric.setVisible(false);
        leftBiometricHighlighted.setVisible(true);
    }//GEN-LAST:event_leftBiometricMouseEntered

    private void leftBiometricHighlightedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftBiometricHighlightedMouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(Color.LIGHT_GRAY);
               leftBiometricHighlighted.setVisible(false);
        leftBiometric.setVisible(true);
    }//GEN-LAST:event_leftBiometricHighlightedMouseExited

    private void rightBiometricMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightBiometricMouseEntered
        // TODO add your handling code here:
         jLabel4.setForeground(Color.WHITE);
         rightBiometric.setVisible(false);
        rightBiometricHighlighted.setVisible(true);
        
    }//GEN-LAST:event_rightBiometricMouseEntered

    private void rightBiometricHighlightedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightBiometricHighlightedMouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(Color.LIGHT_GRAY);
             rightBiometricHighlighted.setVisible(false);
        rightBiometric.setVisible(true);
    }//GEN-LAST:event_rightBiometricHighlightedMouseExited

    private void cameraButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButtonMouseEntered
        // TODO add your handling code here:
        cameraButton.setVisible(false);
        cameraButtonHighlighed.setVisible(true);
    }//GEN-LAST:event_cameraButtonMouseEntered

    private void cameraButtonHighlighedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButtonHighlighedMouseExited
        // TODO add your handling code here:
        cameraButtonHighlighed.setVisible(false);
        cameraButton.setVisible(true);
    }//GEN-LAST:event_cameraButtonHighlighedMouseExited

    private void proceedButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedButtonMouseEntered
        // TODO add your handling code here:
        proceedButton.setVisible(false);
        proceedButtonHighlighted.setVisible(true);
    }//GEN-LAST:event_proceedButtonMouseEntered

    private void proceedButtonHighlightedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedButtonHighlightedMouseExited
        // TODO add your handling code here:
            proceedButtonHighlighted.setVisible(false);
        proceedButton.setVisible(true);
    }//GEN-LAST:event_proceedButtonHighlightedMouseExited

    private void cancelButtonHighlightedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonHighlightedMouseExited
        // TODO add your handling code here:
            cancelButtonHighlighted.setVisible(false);
            cancelButton.setVisible(true);
    }//GEN-LAST:event_cancelButtonHighlightedMouseExited

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered
        // TODO add your handling code here:
        cancelButton.setVisible(false);
        cancelButtonHighlighted.setVisible(true);
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonHighlightedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonHighlightedMouseClicked
        // TODO add your handling code here:
        int confirmExitDialog = JOptionPane.showConfirmDialog(this, "Cancel? All data input will be lost.", "Cancel", JOptionPane.YES_NO_OPTION);
       if(confirmExitDialog == 0){
           HomeForm hf = new HomeForm();
           this.dispose();///
           hf.setVisible(true);
           
       }
    }//GEN-LAST:event_cancelButtonHighlightedMouseClicked

    private void birthdateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthdateTextMouseClicked
        // TODO add your handling code here:
       jPanel1.setVisible(true);
        
    }//GEN-LAST:event_birthdateTextMouseClicked

    private void selectButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selectButtonMouseExited

    private void selectButtonHighlightedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonHighlightedMouseExited
        // TODO add your handling code here:
        selectButtonHighlighted.setVisible(false);
        selectButtonHighlighted.setEnabled(false);
        selectButton.setVisible(true);
        selectButton.setEnabled(true);
        
    }//GEN-LAST:event_selectButtonHighlightedMouseExited

    private void selectButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonMouseEntered
        // TODO add your handling code here:
        selectButton.setVisible(false);
        selectButton.setEnabled(false);
        selectButtonHighlighted.setVisible(true);
        selectButtonHighlighted.setEnabled(true);
    }//GEN-LAST:event_selectButtonMouseEntered

    private void selectButtonHighlightedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonHighlightedMouseClicked
        // TODO add your handling code here:
        birthdateText.setText(dateChooserBirthdate.getSelectedDate());
        selectButtonHighlighted.setVisible(false);
        jPanel1.setVisible(false);

       Thread clock = new Thread(){
           public void run(){
           for(;;){
            
        Calendar cal = Calendar.getInstance();
        GregorianCalendar gc = new GregorianCalendar();
      
        int year = gc.get(Calendar.YEAR);
      
        try{
        ageText.setText(String.valueOf(year - Integer.valueOf(dateChooserBirthdate.getSelectedDate().substring(6, 10))));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Date is not valid. Check carefully");
        
        }
      
               try {
                   sleep(100000);
               } catch (InterruptedException ex) {
                   Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
           }
       
       };
       
       clock.start();
        
    }//GEN-LAST:event_selectButtonHighlightedMouseClicked

    private void dateChooserBirthdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateChooserBirthdateMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dateChooserBirthdateMouseClicked

    private void dateChooserBirthdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateChooserBirthdateMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dateChooserBirthdateMouseEntered

    private void dateChooserBirthdateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dateChooserBirthdateInputMethodTextChanged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_dateChooserBirthdateInputMethodTextChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void firstnameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameTextFocusGained
        // TODO add your handling code here:
        firstnameLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_firstnameTextFocusGained

    private void firstnameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameTextFocusLost
        // TODO add your handling code here:
        firstnameLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_firstnameTextFocusLost

    private void middlenameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenameTextFocusGained
        // TODO add your handling code here:
        middlenameLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_middlenameTextFocusGained

    private void middlenameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenameTextFocusLost
        // TODO add your handling code here:
        middlenameLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_middlenameTextFocusLost

    private void lastnameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameTextFocusGained
        // TODO add your handling code here:
        lastnameLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_lastnameTextFocusGained

    private void lastnameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameTextFocusLost
        // TODO add your handling code here:
        lastnameLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lastnameTextFocusLost

    private void addressTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFocusGained
        // TODO add your handling code here:
        addressLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_addressTextFocusGained

    private void addressTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFocusLost
        // TODO add your handling code here:
        addressLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_addressTextFocusLost

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        birthdateLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden
        // TODO add your handling code here:
        birthdateLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jPanel1ComponentHidden

    private void genderCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genderCBFocusGained
        // TODO add your handling code here:
        genderLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_genderCBFocusGained

    private void genderCBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genderCBFocusLost
        // TODO add your handling code here:
        genderLabel.setForeground(Color.LIGHT_GRAY);
        
    }//GEN-LAST:event_genderCBFocusLost

    private void heightTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heightTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextMouseClicked

    private void weightText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightText1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_weightText1MouseClicked

    private void vehicleUsedTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleUsedTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleUsedTextMouseClicked

    private void licenseNoTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_licenseNoTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNoTextMouseClicked

    private void bloodTypeCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodTypeCBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeCBFocusGained

    private void bloodTypeCBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodTypeCBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeCBFocusLost

    private void resCodeCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resCodeCBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_resCodeCBFocusGained

    private void resCodeCBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resCodeCBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_resCodeCBFocusLost

    private void heightTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightTextFocusGained
        // TODO add your handling code here:
        heightLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_heightTextFocusGained

    private void heightTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightTextFocusLost
        // TODO add your handling code here:
         heightLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_heightTextFocusLost

    private void weightText1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightText1FocusGained
        // TODO add your handling code here:
        weightLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_weightText1FocusGained

    private void weightText1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightText1FocusLost
        // TODO add your handling code here:
        weightLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_weightText1FocusLost

    private void vehicleUsedTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vehicleUsedTextFocusGained
        // TODO add your handling code here:
        vehicleUsedLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_vehicleUsedTextFocusGained

    private void vehicleUsedTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vehicleUsedTextFocusLost
        // TODO add your handling code here:
        vehicleUsedLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_vehicleUsedTextFocusLost

    private void licenseNoTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseNoTextFocusGained
        // TODO add your handling code here:
        licenceNumberLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_licenseNoTextFocusGained

    private void licenseNoTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseNoTextFocusLost
        // TODO add your handling code here:
                licenceNumberLabel.setForeground(Color.LIGHT_GRAY);

    }//GEN-LAST:event_licenseNoTextFocusLost

    private void cameraButtonHighlighedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButtonHighlighedMouseClicked
 
        
    }//GEN-LAST:event_cameraButtonHighlighedMouseClicked

    private void proceedButtonHighlightedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedButtonHighlightedMouseClicked
        // TODO add your handling code here:
        
        String firstname, middlename, lastname, address, birthdate, gender, bloodType, resCode, licenseNumber, vehicleUsed;
        double height, weight;
        int age;
        String photo;
        
        firstname = firstnameText.getText().toString();
        middlename = middlenameText.getText().toString();
        lastname = lastnameText.getText().toString();
        address = addressText.getText().toString();
        birthdate = birthdateText.getText().toString();
        gender = genderCB.getSelectedItem().toString();
        bloodType = bloodTypeCB.getSelectedItem().toString();
        resCode = resCodeCB.getSelectedItem().toString();
        licenseNumber = licenseNoText.getText().toString();
        vehicleUsed = vehicleUsedText.getText().toString();
        height = Double.valueOf(heightText.getText().toString());
        weight = Double.valueOf(weightText1.getText().toString());
        age = Integer.valueOf(ageText.getText().toString());
        photo = "hehe";
        
        try {
     
           String getCount = "select id from cvarst.registration";
           int count = 0;
            ResultSet resultSet = st.executeQuery(getCount);
            while(resultSet.next()){
                count = resultSet.getInt("id");
            }
            
            ps = cn.prepareStatement("insert into cvarst.registration (id, firstname, middlename, lastname,"
                    + " address, birthdate, gender, age, height,"
                    + " weight, blood_type, res_code, vehicle_used,"
                    + " license_number, photo) values"
                    + "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            
            ps.setInt(1, count + 1);
            ps.setString(2, firstname);
            ps.setString(3, middlename);
            ps.setString(4, lastname);
            ps.setString(5, address);
            ps.setString(6, birthdate);
            ps.setString(7, gender);
            ps.setInt(8, age);
            ps.setDouble(9, height);
            ps.setDouble(10, weight);
            ps.setString(11, bloodType);
            ps.setString(12, resCode);
            ps.setString(13, vehicleUsed);
            ps.setString(14, licenseNumber);
            ps.setString(15, photo);
            ps.executeUpdate();
            cn.close();
            ps.close();
            JOptionPane.showMessageDialog(null, "Registered de account Successfully");
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        ColorBlindTestForm btf = new ColorBlindTestForm();
        this.dispose();
        btf.setVisible(true);
    }//GEN-LAST:event_proceedButtonHighlightedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageText;
    private javax.swing.JLabel birthdateLabel;
    private javax.swing.JTextField birthdateText;
    private javax.swing.JComboBox<String> bloodTypeCB;
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JLabel cameraButton;
    private javax.swing.JLabel cameraButtonHighlighed;
    private javax.swing.JPanel cameraFeed;
    private javax.swing.JLabel cancelButton;
    private javax.swing.JLabel cancelButtonHighlighted;
    private cambodia.raven.DateChooser dateChooserBirthdate;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel heightLabel1;
    private javax.swing.JTextField heightText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JLabel leftBiometric;
    private javax.swing.JLabel leftBiometricHighlighted;
    private javax.swing.JLabel licenceNumberLabel;
    private javax.swing.JTextField licenseNoText;
    private javax.swing.JLabel middlenameLabel;
    private javax.swing.JTextField middlenameText;
    private javax.swing.JLabel proceedButton;
    private javax.swing.JLabel proceedButtonHighlighted;
    private javax.swing.JComboBox<String> resCodeCB;
    private javax.swing.JLabel resCodeLabel;
    private javax.swing.JLabel rightBiometric;
    private javax.swing.JLabel rightBiometricHighlighted;
    private javax.swing.JLabel selectButton;
    private javax.swing.JLabel selectButtonHighlighted;
    private javax.swing.JLabel vehicleUsedLabel;
    private javax.swing.JTextField vehicleUsedText;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightLabel1;
    private javax.swing.JTextField weightText1;
    // End of variables declaration//GEN-END:variables
}
