/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.Tests;

import com.sun.media.BasicPlayer;
import com.sun.media.MediaPlayer;
import java.awt.Color;
import java.awt.Point;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStream;
import javax.print.attribute.standard.Media;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javazoom.jl.player.Player;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author edison
 */
public class AuditoryTestForm extends javax.swing.JFrame {

    /**
     * Creates new form AuditoryTestForm
     */
    long total_length;
    long pause;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    File myFile;
    MediaPlayer mp;
    Media me;
    
    
    public AuditoryTestForm() {
        initComponents();
        setSize(875, 551);
        setResizable(false);
        this.setBackground(new Color(23, 23,23 ,150));
        jLabel4.setBackground(new Color(23, 23,23));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        nextButtonHighlighted.setVisible(false);
        nextButtonPressed.setVisible(false);
        JButton inputButtons[] = {buttonPlay,buttonStop};
              for (int i=0; i < inputButtons.length; i++){
            inputButtons[i].setOpaque(false);
            inputButtons[i].setContentAreaFilled(false);
            inputButtons[i].setBorderPainted(true);
        }
          hPlay.setVisible(false);
       
          hStop.setVisible(false);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionImage = new javax.swing.JLabel();
        audioTrack = new javax.swing.JSlider();
        hPlay = new javax.swing.JLabel();
        hStop = new javax.swing.JLabel();
        nextButtonPressed = new javax.swing.JLabel();
        nextButtonHighlighted = new javax.swing.JLabel();
        nextButton = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonPlay = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        questionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AuditoryTest/headphone.png"))); // NOI18N
        getContentPane().add(questionImage);
        questionImage.setBounds(60, 130, 250, 270);
        getContentPane().add(audioTrack);
        audioTrack.setBounds(510, 330, 210, 39);

        hPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/highlighted.png"))); // NOI18N
        getContentPane().add(hPlay);
        hPlay.setBounds(510, 380, 100, 40);

        hStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/highlighted.png"))); // NOI18N
        getContentPane().add(hStop);
        hStop.setBounds(620, 380, 100, 40);

        nextButtonPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/nextButtonPressed.png"))); // NOI18N
        nextButtonPressed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextButtonPressedMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonPressedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonPressedMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonPressedMouseEntered(evt);
            }
        });
        nextButtonPressed.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nextButtonPressedComponentShown(evt);
            }
        });
        getContentPane().add(nextButtonPressed);
        nextButtonPressed.setBounds(650, 490, 190, 29);

        nextButtonHighlighted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secondary_Images/nextButtonHighlighted.png"))); // NOI18N
        nextButtonHighlighted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextButtonHighlightedMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonHighlightedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonHighlightedMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonHighlightedMouseEntered(evt);
            }
        });
        getContentPane().add(nextButtonHighlighted);
        nextButtonHighlighted.setBounds(650, 490, 190, 29);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nextButton.png"))); // NOI18N
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(650, 490, 190, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AuditoryTest/questionDisplay.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 70, 230, 33);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AuditoryTest/title.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 30, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MinimizeButton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(831, 0, 50, 20);

        jLabel2.setBackground(new java.awt.Color(3, 72, 83));
        jLabel2.setOpaque(true);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 20);

        jLabel6.setBackground(new java.awt.Color(17, 107, 121));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 370, 550);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 20)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Left Ear");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 300, 210, 24);

        buttonPlay.setFont(new java.awt.Font("Ubuntu Condensed", 0, 15)); // NOI18N
        buttonPlay.setForeground(java.awt.Color.white);
        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AuditoryTest/play_button.png"))); // NOI18N
        buttonPlay.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonPlayMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPlayMouseClicked(evt);
            }
        });
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlay);
        buttonPlay.setBounds(510, 380, 100, 40);

        buttonStop.setFont(new java.awt.Font("Ubuntu Condensed", 0, 15)); // NOI18N
        buttonStop.setForeground(java.awt.Color.white);
        buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AuditoryTest/stop_button.png"))); // NOI18N
        buttonStop.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonStopMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonStopMouseReleased(evt);
            }
        });
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        getContentPane().add(buttonStop);
        buttonStop.setBounds(620, 380, 100, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AuditoryTest/left_ear.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 100, 210, 190);

        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 20, 510, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:

        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(AuditoryTestForm.ICONIFIED);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void nextButtonPressedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPressedMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_nextButtonPressedMouseReleased

    private void nextButtonPressedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPressedMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_nextButtonPressedMouseClicked

    private void nextButtonPressedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPressedMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonPressedMouseExited

    private void nextButtonPressedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPressedMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonPressedMouseEntered

    private void nextButtonPressedComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nextButtonPressedComponentShown
        // TODO add your handling code here:
        nextButtonPressed.setVisible(false);
        nextButton.setVisible(true);
    }//GEN-LAST:event_nextButtonPressedComponentShown

    private void nextButtonHighlightedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonHighlightedMousePressed
        // TODO add your handling code here:
        nextButtonHighlighted.setVisible(false);
        nextButtonPressed.setVisible(true);
    }//GEN-LAST:event_nextButtonHighlightedMousePressed

    private void nextButtonHighlightedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonHighlightedMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nextButtonHighlightedMouseClicked

    private void nextButtonHighlightedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonHighlightedMouseExited
        // TODO add your handling code here:
        nextButtonHighlighted.setVisible(false);
        nextButton.setVisible(true);
    }//GEN-LAST:event_nextButtonHighlightedMouseExited

    private void nextButtonHighlightedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonHighlightedMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_nextButtonHighlightedMouseEntered

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_nextButtonMouseClicked

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        // TODO add your handling code here:
        nextButton.setVisible(false);
        nextButtonHighlighted.setVisible(true);
    }//GEN-LAST:event_nextButtonMouseEntered

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        // TODO add your handling code here:
       
        InputStream in;
        try{
//            in = new FileInputStream(new File (getClass().getResource("/Audio/6th.mp4.wav").getPath()));
//            
//            AudioStream audioStream = new AudioStream(in);
//            AudioPlayer.player.start(audioStream);

            FIS = new FileInputStream(new File (getClass().getResource("/Audio/lostwithoutyou.mp3").getPath()));
            BIS = new BufferedInputStream(FIS);
            player = new Player(BIS);
            total_length = FIS.available();
            
            new Thread(){
            
                public void run(){
                try{
                    player.play();
                    
               
                }
                catch(Exception e){
                e.printStackTrace();
                }
                }
            }.start();
      
             buttonPlay.setEnabled(false);
             buttonStop.setEnabled(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        // TODO add your handling code here:
        if(player != null){
        
        player.close();
        buttonPlay.setEnabled(true);
        buttonStop.setEnabled(false);
        
                }
    
    }//GEN-LAST:event_buttonStopActionPerformed

    private void buttonPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMousePressed
        // TODO add your handling code here:
        hPlay.setVisible(true);
    }//GEN-LAST:event_buttonPlayMousePressed

    private void buttonPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseReleased
        // TODO add your handling code here:
        hPlay.setVisible(false);
    }//GEN-LAST:event_buttonPlayMouseReleased

    private void buttonStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStopMousePressed
        // TODO add your handling code here:
          hStop.setVisible(true);
    }//GEN-LAST:event_buttonStopMousePressed

    private void buttonStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStopMouseReleased
        // TODO add your handling code here:
          hStop.setVisible(false);
    }//GEN-LAST:event_buttonStopMouseReleased

    private void buttonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditoryTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditoryTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditoryTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditoryTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuditoryTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider audioTrack;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonStop;
    private javax.swing.JLabel hPlay;
    private javax.swing.JLabel hStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nextButton;
    private javax.swing.JLabel nextButtonHighlighted;
    private javax.swing.JLabel nextButtonPressed;
    private javax.swing.JLabel questionImage;
    // End of variables declaration//GEN-END:variables
}
