/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.Tests;

import java.awt.Color;
import java.awt.Point;
import javax.swing.SwingConstants;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author edison
 */
public class VisualAcuitySnellenTestForm extends javax.swing.JFrame {

    /**
     * Creates new form VisualAcuitySnellenTestForm
     */
    public VisualAcuitySnellenTestForm() {
        initComponents();
        setSize(875, 665);
         jLabel1.setBackground(new Color(23, 23,23));
        setResizable(false);
        questionText.setHorizontalAlignment(SwingConstants.CENTER);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        questionText1 = new javax.swing.JLabel();
        questionText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        questionImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(23, 23, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        questionText1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        questionText1.setForeground(java.awt.Color.white);
        questionText1.setText("Question");
        jPanel2.add(questionText1);
        questionText1.setBounds(10, 10, 170, 20);

        questionText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        questionText.setForeground(java.awt.Color.white);
        questionText.setText("Read Line No. 5");
        jPanel2.add(questionText);
        questionText.setBounds(20, 50, 390, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 60, 430, 120);

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 0, 14), java.awt.Color.white)); // NOI18N
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(24, 24, 24));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Vision Right: 20/20");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 180, 140, 30);

        jLabel7.setBackground(new java.awt.Color(24, 24, 24));
        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Examination Result");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 0, 400, 30);

        jLabel8.setBackground(new java.awt.Color(24, 24, 24));
        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Colorblind: 7/7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 60, 140, 30);

        jLabel9.setBackground(new java.awt.Color(24, 24, 24));
        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Auditory:  2/3");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 100, 140, 30);

        jLabel10.setBackground(new java.awt.Color(24, 24, 24));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Vision Left: 20/20");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 140, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 230, 430, 250);

        jButton1.setText("Wrong");
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 560, 100, 50);

        jButton2.setText("Correct");
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 560, 100, 50);

        questionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VisualAcuitySnellen/1-1.jpg"))); // NOI18N
        getContentPane().add(questionImage);
        questionImage.setBounds(30, 90, 310, 500);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/title_visual_acuity_snellen.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 30, 280, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MinimizeButton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(831, 0, 50, 20);

        jLabel2.setBackground(new java.awt.Color(3, 72, 83));
        jLabel2.setOpaque(true);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 20);

        jLabel6.setBackground(new java.awt.Color(17, 107, 121));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 370, 670);

        jLabel1.setBackground(new java.awt.Color(23, 23, 23));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 510, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:

        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(VisualAcuitySnellenTestForm.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualAcuitySnellenTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualAcuitySnellenTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualAcuitySnellenTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualAcuitySnellenTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualAcuitySnellenTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel questionImage;
    private javax.swing.JLabel questionText;
    private javax.swing.JLabel questionText1;
    // End of variables declaration//GEN-END:variables
}
