/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.Tests;

import java.awt.Color;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import project.Examinee;
import project.HomeForm;
import project.RegistrationForm;

/**
 *
 * @author edison
 */
public class VisualAcuityBailyLoviTestForm extends javax.swing.JFrame {

    /**
     * Creates new form VisualAcuityBailyLoviTestForm
     */
    private Connection cn;
    private PreparedStatement ps;
    private Statement st;
    private Map<Object, Object> content;
    private int currentItemFinished = 0, totalPoints = 0, userId = 0;
    private ArrayList questionImages = new ArrayList(), questionTexts = new ArrayList();
  
    private int colorBlindScore = 0, colorBlindTotalPoints=0, auditoryScore=0, auditoryTotalPoints=0, visualSnellenScore = 0, visualSnellenTotal = 0;
    public VisualAcuityBailyLoviTestForm(){
            initComponents();
        setSize(978, 665);
        jLabel1.setBackground(new Color(23, 23,23));
        setResizable(false);
        
        colorBlindScore = Examinee.getColorBlindExamineePoints();
        colorBlindTotalPoints = Examinee.getColorBlindTotalPoints();
        auditoryScore = Examinee.getAuditoryExamineePoints();
        auditoryTotalPoints = Examinee.getAuditoryTotalPoints();
        visualSnellenScore = Examinee.getVisualSnellenExamineePoints();
        visualSnellenTotal  = Examinee.getVisualSnellenTotalPoints();
        userId = Examinee.getExamineeID();
        
        content = new HashMap<Object, Object>();
        questionText.setHorizontalAlignment(SwingConstants.CENTER);
        try{
        Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            String getData = "SELECT * FROM cvarst.VisualAcuityBailyTest";
            ResultSet rs = st.executeQuery(getData);
            while(rs.next()){
                ImageIcon icon = new ImageIcon((byte[]) rs.getBytes("Picture"));
                questionImages.add(icon);
                questionTexts.add(rs.getString("Question"));
            }
           
        }
        catch(Exception e){
        e.printStackTrace();
        }
       for (int i = 0; i < questionImages.size(); i++){
        content.put(questionImages.get(i), questionTexts.get(i));
        System.out.println(String.valueOf(questionImages.get(i)) + " " + questionTexts.get(i));
        }
      
       questionText.setText(String.valueOf(questionTexts.get(0)));
       imageQuestion.setIcon((ImageIcon) questionImages.get(0));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        imageQuestion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        questionText1 = new javax.swing.JLabel();
        questionText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        answerCorrect = new javax.swing.JLabel();
        answerWrong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(3, 72, 83));
        jLabel2.setOpaque(true);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 980, 20);

        imageQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VisualAcuityBailyLovi/1-2.jpg"))); // NOI18N
        getContentPane().add(imageQuestion);
        imageQuestion.setBounds(60, 140, 260, 300);

        jPanel2.setBackground(new java.awt.Color(23, 23, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        questionText1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        questionText1.setForeground(java.awt.Color.white);
        questionText1.setText("Question");
        jPanel2.add(questionText1);
        questionText1.setBounds(10, 10, 170, 20);

        questionText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        questionText.setForeground(java.awt.Color.white);
        questionText.setText("Read Line No. 5");
        jPanel2.add(questionText);
        questionText.setBounds(20, 50, 500, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 60, 540, 120);

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(24, 24, 24));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Vision Right: 20/20");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 180, 140, 30);

        jLabel7.setBackground(new java.awt.Color(24, 24, 24));
        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Examination Result");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 0, 400, 30);

        jLabel8.setBackground(new java.awt.Color(24, 24, 24));
        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Colorblind: 7/7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 60, 140, 30);

        jLabel9.setBackground(new java.awt.Color(24, 24, 24));
        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Auditory:  2/3");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 100, 140, 30);

        jLabel10.setBackground(new java.awt.Color(24, 24, 24));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Vision Left: 20/20");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 140, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 230, 540, 250);

        answerCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_choice.png"))); // NOI18N
        answerCorrect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                answerCorrectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                answerCorrectMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerCorrectMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                answerCorrectMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                answerCorrectMouseEntered(evt);
            }
        });
        getContentPane().add(answerCorrect);
        answerCorrect.setBounds(620, 560, 60, 60);

        answerWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong_answer.png"))); // NOI18N
        answerWrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                answerWrongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                answerWrongMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerWrongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                answerWrongMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                answerWrongMouseEntered(evt);
            }
        });
        getContentPane().add(answerWrong);
        answerWrong.setBounds(700, 560, 60, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/title_visual_baily_lovi.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 30, 310, 30);

        jLabel6.setBackground(new java.awt.Color(17, 107, 121));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 370, 670);

        jLabel1.setBackground(new java.awt.Color(23, 23, 23));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 610, 650);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MinimizeButton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(940, 0, 50, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerCorrectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerCorrectMousePressed
        answerCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_choice.png")));
    }//GEN-LAST:event_answerCorrectMousePressed

    private void answerCorrectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerCorrectMouseReleased
        // TODO add your handling code here:
        answerCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_highlighted.png")));
    }//GEN-LAST:event_answerCorrectMouseReleased

        private void finished(){
    
        Examinee examinee = new Examinee();
        examinee.setUserID(userId);
        examinee.setColorblindExamineePoints(colorBlindScore);
        examinee.setColorblindTotalPoints(colorBlindTotalPoints);
        examinee.setAuditoryExamineePoints(auditoryScore);
        examinee.setAuditoryTotalPoints(auditoryTotalPoints);
        examinee.setVisualSnellenExamineePoints(visualSnellenScore);
        examinee.setVisualSnellenTotalPoints(visualSnellenTotal);
        
        examinee.setVisualBailyExamineePoints(totalPoints);
        examinee.setVisualBailyTotalPoints(questionImages.size());
        
        
//        
//        JOptionPane.showMessageDialog(null, 
//                
//                String.valueOf(
//                examinee.getColorBlindExamineePoints() + " " +
//                        examinee.getColorBlindExamineePoints() + " " +
//                        examinee.getAuditoryExamineePoints() +" " +
//                        examinee.getAuditoryTotalPoints() +" " +
//                        examinee.getVisualSnellenExamineePoints() +" " +
//                        examinee.getVisualSnellenTotalPoints() +" " +
//                        examinee.getVisualBailyExamineePoints() + " " +
//                        examinee.getVisualBailyTotalPoints()
//                        
//                
//                        )
//                );


        try {
            
            ps = cn.prepareStatement("update cvarst.registration SET ColorblindScore = ? , ColorblindTotalPoints = ?"
                    + ", AuditoryScore = ?, AuditoryTotalPoints = ?, VisualSnellenScore = ? , VisualSnellenTotalPoints = ?, VisualBailyScore = ?, VisualBailyTotalPoints = ? where id = '"+ Examinee.getExamineeID()+"'");
            
            
//            (ColorblindScore , ColorblindTotalPoints, "
//                    + "AuditoryScore, AuditoryTotalPoints, "
//                    + "VisualSnellenScore, VisualSnellenTotalPoints, "
//                    + "VisualBailyScore, VisualBailyTotalPoints)
            ps.setInt(1, Examinee.getColorBlindExamineePoints());
            ps.setInt(2, Examinee.getColorBlindTotalPoints()); //firstname
            ps.setInt(3, Examinee.getAuditoryExamineePoints());
            ps.setInt(4, Examinee.getAuditoryTotalPoints());
            ps.setInt(5, Examinee.getVisualSnellenExamineePoints());
            ps.setInt(6, Examinee.getVisualSnellenTotalPoints());
            ps.setInt(7, Examinee.getVisualBailyExamineePoints());
            ps.setInt(8, Examinee.getVisualBailyTotalPoints());
       
            ps.executeUpdate();
            cn.close();
            ps.close();
            JOptionPane.showMessageDialog(null, "Exam completed. ");
            HomeForm hF = new HomeForm();
            this.dispose();
            hF.setVisible(true);
            
        } catch (Exception e) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void answerCorrectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerCorrectMouseClicked
        // TODO add your handling code here:

        if(currentItemFinished < questionImages.size()){

            imageQuestion.setIcon((ImageIcon) questionImages.get(currentItemFinished));
            questionText.setText(String.valueOf(questionTexts.get(currentItemFinished)));
            totalPoints++;
            currentItemFinished++;

        }
        else{
            finished();
            JOptionPane.showMessageDialog(null, "Done. Total Points: " + String.valueOf(totalPoints));
        }

    }//GEN-LAST:event_answerCorrectMouseClicked

    private void answerCorrectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerCorrectMouseExited
        // TODO add your handling code here:
        answerCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_choice.png")));
    }//GEN-LAST:event_answerCorrectMouseExited

    private void answerCorrectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerCorrectMouseEntered
        // TODO add your handling code here:
        answerCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_highlighted.png")));
    }//GEN-LAST:event_answerCorrectMouseEntered

    private void answerWrongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerWrongMousePressed
        // TODO add your handling code here:
        answerWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong_answer.png")));
    }//GEN-LAST:event_answerWrongMousePressed

    private void answerWrongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerWrongMouseReleased
        // TODO add your handling code here:
        answerWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong_highlighted.png")));
    }//GEN-LAST:event_answerWrongMouseReleased

    private void answerWrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerWrongMouseClicked
        // TODO add your handling code here:
        if(currentItemFinished < questionImages.size()){

            imageQuestion.setIcon((ImageIcon) questionImages.get(currentItemFinished));
            questionText.setText(String.valueOf(questionTexts.get(currentItemFinished)));

            currentItemFinished++;

        }
        else{
            finished();
            JOptionPane.showMessageDialog(null, "Done. Total Points: " + String.valueOf(totalPoints));
        }
    }//GEN-LAST:event_answerWrongMouseClicked

    private void answerWrongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerWrongMouseExited
        // TODO add your handling code here:
        answerWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong_answer.png")));
    }//GEN-LAST:event_answerWrongMouseExited

    private void answerWrongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerWrongMouseEntered
        // TODO add your handling code here:
        answerWrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong_highlighted.png")));
    }//GEN-LAST:event_answerWrongMouseEntered

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:

        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(VisualAcuitySnellenTestForm.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualAcuityBailyLoviTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualAcuityBailyLoviTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualAcuityBailyLoviTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualAcuityBailyLoviTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualAcuityBailyLoviTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerCorrect;
    private javax.swing.JLabel answerWrong;
    private javax.swing.JLabel imageQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel questionText;
    private javax.swing.JLabel questionText1;
    // End of variables declaration//GEN-END:variables
}
